! *****************************************************************************
MODULE IO
! *****************************************************************************

USE VARS

IMPLICIT NONE

CONTAINS

! *****************************************************************************
SUBROUTINE SET_NAMELIST_DEFAULTS
! *****************************************************************************

INPUT_DIRECTORY                        = 'null'
OUTPUT_DIRECTORY                       = 'null'
FUELS_AND_TOPOGRAPHY_DIRECTORY         = 'null'
WEATHER_DIRECTORY                      = 'null'
FIRE_DYNAMICS_DIRECTORY                = 'null'
A_SRS                                  = 'null'
ASP_FILENAME                           = 'null'
CBD_FILENAME                           = 'null'
CBH_FILENAME                           = 'null'
CC_FILENAME                            = 'null'
CH_FILENAME                            = 'null'
DEM_FILENAME                           = 'null'
FBFM_FILENAME                          = 'null'
MFRI_FILENAME                          = 'null'
SLP_FILENAME                           = 'null'
WAF_FILENAME                           = 'null'
WS_FILENAME                            = 'null'
WD_FILENAME                            = 'null'
M1_FILENAME                            = 'null'
M10_FILENAME                           = 'null'
M100_FILENAME                          = 'null'
MLH_FILENAME                           = 'null'
MLW_FILENAME                           = 'null'
FLAME_LENGTH_FILENAME                  = 'null'
FLIN_FILENAME                          = 'null'
VELOCITY_DMS_FILENAME                  = 'null'
HPUA_FILENAME                          = 'null'
IR_FILENAME                            = 'null'
MEQ_FILENAME                           = 'null'
RH_FILENAME                            = 'null'
TMP_FILENAME                           = 'null'
FFWI_FILENAME                          = 'null'
MFFWI_FILENAME                         = 'null'
UWIND_FILENAME                         = 'null'
VWIND_FILENAME                         = 'null'
MISCELLANEOUS_INPUTS_DIRECTORY         = 'null'
PIGN_FILENAME                          = 'null'
PIGN_LBF_FILENAME                      = 'null'
PIGN_WS_FILENAME                       = 'null'
PIGN_LBF_AVG_FILENAME                  = 'null'
PCT_WS_ABOVE_THRESHOLD_FILENAME        = 'null'
PIGN_PCT_WS_ABOVE_THRESHOLD_FILENAME   = 'null'
WS_THRESHOLD                           = 0. 
ADD_TO_MEQ                             = 0.
NORMALIZE_PIGN                         = .FALSE. 

FUEL_MODEL_FILE                        = 'fuel_models.csv'
COMPRESS                               = .FALSE. 

! Map generator variables:
DISCRETE_OR_CONTINUOUS                           = 'null'
ADDITIVE_OR_MULTIPLICATIVE                       = 'null'
NUMBER_OF_COMPONENTS                             = -1
INPUT_DIRECTORY_FOR_COMPONENT              (:)   = 'null'
FILENAME_OF_COMPONENT                      (:)   = 'null'
NUMBER_OF_CATEGORIES_FOR_COMPONENT         (:)   = -1
COLOR_TABLE_FOR_COMPONENT                  (:)   = 'null'
CATEGORY_THRESHOLDS_FOR_COMPONENT          (:,:) = -9E9
OUTPUT_FILENAME_OF_CATEGORIZED_COMPONENT   (1  ) = 'null'
NUMBER_OF_CATEGORIES_FOR_FINAL_HAZARD_SCALE      = -1
CATEGORY_THRESHOLDS_FOR_FINAL_HAZARD_SCALE (  :) = -9E9
OUTPUT_FILENAME_OF_FINAL_HAZARD_SCALE            = 'null'
WEIGHTING_FACTOR_FOR_COMPONENT             (:  ) = 1.
CATEGORY_SCORES_FOR_COMPONENT              (:,:) = -9E9
CATEGORY_SCORES_FOR_FINAL_HAZARD_SCALE     (  :) = -9E9
COLOR_TABLE_FOR_FINAL_HAZARD_SCALE         (:)   = 'null'
USE_3BY3_SCORING                                 = .FALSE.
THREE_BY_THREE_SCORING                   (:,:,:) = -9E9

! Fire dynamics variables:
M1_MINUS_MEQ        = -9999.
M10_MINUS_MEQ       = -9999.
M100_MINUS_MEQ      = -9999.
LH_MOISTURE_CONTENT = -9999.
LW_MOISTURE_CONTENT = -9999.

! Units for Fosberg:
WS_IN_METERS_PER_SECOND = .FALSE.
TMP_IN_CELSIUS          = .FALSE.
LOWPASS_TEMP            = 5000.0

! Ignition axis:
NBANDS_FOR_IGNITION_AXIS = 1

! i/o:
PATH_TO_GDAL                   = '/usr/local/gdal-2.0.1/bin/'
SCRATCH                        = '/media/scratch/'

! Misc:
CBD_TIMES_100 = .TRUE. 
CBH_TIMES_10  = .TRUE.
CC_IN_PERCENT = .TRUE.
CH_TIMES_10   = .TRUE.

! Moving average:
INPUT_RASTER_FILENAME  = 'null'
OUTPUT_RASTER_FILENAME = 'null'
NBANDS_TO_AVERAGE      = 1

! HDW:
SH_FILENAME  = 'null'
P0_FILENAME  = 'null'
VPD_FILENAME = 'null'
HDW_FILENAME = 'null'
TMP_UNITS   = 'F'

! KBDI
NUM_INTERVALS_PER_DAY = -1
PRECIP_FILENAME       = 'null'
PRECIP_AVG_FILENAME   = 'null'
KBDI0_FILENAME        = 'null'
KBDI_FILENAME         = 'null'
FAF_FILENAME          = 'null'
PRECIP_MULT           = 1D0

! OUTPUTS
CONVERT_TO_GEOTIFF    = .TRUE.
COMPRESS              = .FALSE.

! Wind speed and direction
ROTATE_WINDS          = .FALSE.

! *****************************************************************************
END SUBROUTINE SET_NAMELIST_DEFAULTS
! *****************************************************************************

! *****************************************************************************
SUBROUTINE READ_BIL_RASTER(RASTER,FN)
! *****************************************************************************

USE VARS, ONLY: RASTER_TYPE, LUINPUT, DELETECOMMAND, PATH_TO_GDAL
#ifdef __INTEL_COMPILER
USE IFPORT
#endif

IMPLICIT NONE

TYPE (RASTER_TYPE), INTENT(OUT) :: RASTER
CHARACTER(400), INTENT (IN) :: FN
CHARACTER(400) :: FNHDR, FNBIL, FNTIF, FNPRJ, FNXML, SHELLSTR
INTEGER :: I, IROW, ICOL, IOS, LRECL, ICOLSTART, ICOLSTOP, IBAND, ISTATUS
CHARACTER(400), DIMENSION(1:14) :: BIL_HDR
REAL, ALLOCATABLE, DIMENSION(:) :: RVALUES
INTEGER*2, ALLOCATABLE, DIMENSION(:) :: I2VALUES

FNHDR = TRIM(FN) // '.hdr'
FNBIL = TRIM(FN) // '.bil'
FNTIF = TRIM(FN) // '.tif'
FNPRJ = TRIM(FN) // '.prj'
FNXML = TRIM(FNBIL) // '.aux.xml'

SHELLSTR = TRIM(PATH_TO_GDAL) // "gdal_translate -of EHdr " // TRIM(FNTIF) // " " // TRIM(FNBIL)
WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))

!Open and parse bil header:
OPEN(LUINPUT,FILE=TRIM(FNHDR),FORM='FORMATTED',STATUS='OLD',IOSTAT=IOS) 
IF (IOS .GT. 0) THEN
   WRITE(*,*) 'Problem opening bil header file ', TRIM(FNHDR)
   CONTINUE
ENDIF

WRITE(*,*) 'Reading bil header file'

READ(LUINPUT,100,IOSTAT=IOS) BIL_HDR(01);  READ(BIL_HDR(01)(16:16),*) RASTER%BYTEORDER
READ(LUINPUT,100,IOSTAT=IOS) BIL_HDR(02);  READ(BIL_HDR(02)(16:18),*) RASTER%LAYOUT
READ(LUINPUT,100,IOSTAT=IOS) BIL_HDR(03);  READ(BIL_HDR(03)(16:30),*) RASTER%NROWS
READ(LUINPUT,100,IOSTAT=IOS) BIL_HDR(04);  READ(BIL_HDR(04)(16:30),*) RASTER%NCOLS
READ(LUINPUT,100,IOSTAT=IOS) BIL_HDR(05);  READ(BIL_HDR(05)(16:30),*) RASTER%NBANDS
READ(LUINPUT,100,IOSTAT=IOS) BIL_HDR(06);  READ(BIL_HDR(06)(16:30),*) RASTER%NBITS
READ(LUINPUT,100,IOSTAT=IOS) BIL_HDR(07);  READ(BIL_HDR(07)(16:30),*) RASTER%BANDROWBYTES
READ(LUINPUT,100,IOSTAT=IOS) BIL_HDR(08);  READ(BIL_HDR(08)(16:30),*) RASTER%TOTALROWBYTES
READ(LUINPUT,100,IOSTAT=IOS) BIL_HDR(09);  READ(BIL_HDR(09)(16:25),*) RASTER%PIXELTYPE
READ(LUINPUT,100,IOSTAT=IOS) BIL_HDR(10);  READ(BIL_HDR(10)(16:30),*) RASTER%ULXMAP
READ(LUINPUT,100,IOSTAT=IOS) BIL_HDR(11);  READ(BIL_HDR(11)(16:30),*) RASTER%ULYMAP
READ(LUINPUT,100,IOSTAT=IOS) BIL_HDR(12);  READ(BIL_HDR(12)(16:30),*) RASTER%XDIM
READ(LUINPUT,100,IOSTAT=IOS) BIL_HDR(13);  READ(BIL_HDR(13)(16:30),*) RASTER%YDIM

!IF (RASTER%XDIM .NE. RASTER%YDIM) THEN
!   WRITE(*,*) 'Error opening ', TRIM(FNHDR), ' because XDIM is not equal to YDIM.'
!   STOP
!ELSE
!   RASTER%CELLSIZE=RASTER%XDIM
!ENDIF

READ(LUINPUT,100,IOSTAT=IOS) BIL_HDR(14);  READ(BIL_HDR(14)(16:30),*) RASTER%NODATA_VALUE
IF (IOS .NE. 0) THEN
   WRITE(*,*) 'Error opening ', TRIM(FNHDR), ' because NODATA is not set.'
   STOP
ENDIF
CLOSE(LUINPUT,IOSTAT=IOS)

RASTER%XLLCORNER = RASTER%ULXMAP - 0.5 * RASTER%XDIM
RASTER%YLLCORNER = RASTER%ULYMAP + 0.5 * RASTER%YDIM - REAL(RASTER%NROWS) * RASTER%YDIM 

SELECT CASE(TRIM(RASTER%PIXELTYPE))

   CASE('FLOAT')
!     Allocate arrays as appropriate:
      IF (.NOT. ALLOCATED(RASTER%RZT)) THEN
         ALLOCATE(RASTER%RZT(1:RASTER%NBANDS,1:RASTER%NCOLS,1:RASTER%NROWS) )
         RASTER%RZT(:,:,:) = RASTER%NODATA_VALUE
      ENDIF

      ALLOCATE(RVALUES(1:RASTER%NBANDS*RASTER%NCOLS))

!Open raster bil file:
      INQUIRE (IOLENGTH=LRECL) RVALUES(:) 

      OPEN(LUINPUT, FILE=TRIM(FNBIL), ACCESS='DIRECT', STATUS='OLD', RECL=LRECL, IOSTAT=IOS) 
      IF (IOS .GT. 0) THEN
         WRITE(*,*) 'Problem opening raster file ', TRIM(FNBIL)
         STOP
      ENDIF

      I = RASTER%NROWS + 1
      DO IROW = 1, RASTER%NROWS
         I = I - 1
         READ(LUINPUT,REC=IROW,IOSTAT=IOS) (RVALUES(ICOL) , ICOL = 1, RASTER%NBANDS*RASTER%NCOLS)
         ICOLSTART = 1
         DO IBAND = 1, RASTER%NBANDS
            ICOLSTOP = ICOLSTART + RASTER%NCOLS - 1
            RASTER%RZT(IBAND,1:RASTER%NCOLS,I) = RVALUES(ICOLSTART:ICOLSTOP)
            ICOLSTART = ICOLSTOP + 1
         ENDDO
      ENDDO

      DEALLOCATE(RVALUES)

   CASE('SIGNEDINT')
!     Allocate arrays as appropriate:
      IF (.NOT. ALLOCATED(RASTER%I2ZT)) THEN
         ALLOCATE(RASTER%I2ZT(1:RASTER%NBANDS,1:RASTER%NCOLS,1:RASTER%NROWS) )
         RASTER%I2ZT(:,:,:) = NINT(RASTER%NODATA_VALUE)
      ENDIF

      ALLOCATE(I2VALUES(1:RASTER%NBANDS*RASTER%NCOLS))

!Open raster bil file:
      INQUIRE (IOLENGTH=LRECL) I2VALUES(:) 

      OPEN(LUINPUT, FILE=TRIM(FNBIL), ACCESS='DIRECT', STATUS='OLD', RECL=LRECL, IOSTAT=IOS) 
      IF (IOS .GT. 0) THEN
         WRITE(*,*) 'Problem opening raster file ', TRIM(FNBIL)
         STOP
      ENDIF

      I = RASTER%NROWS + 1
      DO IROW = 1, RASTER%NROWS
         I = I - 1
         READ(LUINPUT,REC=IROW,IOSTAT=IOS) (I2VALUES(ICOL) , ICOL = 1, RASTER%NBANDS*RASTER%NCOLS)
         ICOLSTART = 1
         DO IBAND = 1, RASTER%NBANDS
            ICOLSTOP = ICOLSTART + RASTER%NCOLS - 1
            RASTER%I2ZT(IBAND,1:RASTER%NCOLS,I) = I2VALUES(ICOLSTART:ICOLSTOP)
            ICOLSTART = ICOLSTOP + 1
         ENDDO
      ENDDO

      DEALLOCATE(I2VALUES)

   CASE DEFAULT
      CONTINUE

END SELECT

CLOSE(LUINPUT,IOSTAT=IOS)

SHELLSTR = TRIM(DELETECOMMAND) // " " // TRIM(FNBIL); WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))
SHELLSTR = TRIM(DELETECOMMAND) // " " // TRIM(FNHDR); WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))
SHELLSTR = TRIM(DELETECOMMAND) // " " // TRIM(FNPRJ); WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))
SHELLSTR = TRIM(DELETECOMMAND) // " " // TRIM(FNXML); WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))

100 FORMAT(A)

! *****************************************************************************
END SUBROUTINE READ_BIL_RASTER
! *****************************************************************************

! *****************************************************************************
SUBROUTINE READ_BSQ_RASTER(RASTER,INDIR,FN)
! *****************************************************************************

USE VARS, ONLY: RASTER_TYPE, LUINPUT, DELETECOMMAND, PATH_TO_GDAL, SCRATCH
#ifdef __INTEL_COMPILER
USE IFPORT
#endif

IMPLICIT NONE

TYPE (RASTER_TYPE), INTENT(OUT) :: RASTER
CHARACTER(400), INTENT (IN) :: INDIR,FN
CHARACTER(400) :: FNHDR, FNBSQ, FNTIF, FNPRJ, FNXML, SHELLSTR, TEMPSTR
INTEGER :: I, J, IOS, LRECL, IBAND, ISTATUS, ITYPE, IDUMMY, IROW1, IROW2
LOGICAL :: FOUND
REAL, ALLOCATABLE, DIMENSION(:) :: RVALUES
REAL, ALLOCATABLE, DIMENSION(:,:) :: RTEMP
INTEGER*2, ALLOCATABLE, DIMENSION(:) :: I2VALUES
INTEGER*2, ALLOCATABLE, DIMENSION(:,:) :: I2TEMP

IF (TRIM(SCRATCH) .EQ. 'null') THEN
   FNTIF = TRIM(INDIR) // TRIM(FN) // '.tif'
   FNHDR = TRIM(INDIR) // TRIM(FN) // '.hdr'
   FNBSQ = TRIM(INDIR) // TRIM(FN) // '.bsq'
   FNPRJ = TRIM(INDIR) // TRIM(FN) // '.prj'
   FNXML = TRIM(FNBSQ) // '.aux.xml'
ELSE
   FNTIF = TRIM(INDIR) // TRIM(FN) // '.tif'
   FNHDR = TRIM(SCRATCH) // TRIM(FN) // '.hdr'
   FNBSQ = TRIM(SCRATCH) // TRIM(FN) // '.bsq'
   FNPRJ = TRIM(SCRATCH) // TRIM(FN) // '.prj'
   FNXML = TRIM(FNBSQ) // '.aux.xml'
ENDIF

! Convert to ENVI header BSQ format
SHELLSTR = TRIM(PATH_TO_GDAL) // 'gdal_translate -of ENVI -co "INTERLEAVE=BSQ" ' // TRIM(FNTIF) // " " // TRIM(FNBSQ)
!SHELLSTR = TRIM(PATH_TO_GDAL) // 'gdalwarp --config GDAL_CACHEMAX 1000 -multi -of ENVI -co "INTERLEAVE=BSQ" ' // TRIM(FNTIF) // " " // TRIM(FNBSQ)
WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))

!! And remove metadata
!SHELLSTR = TRIM(PATH_TO_GDAL) // 'gdal_edit.py -unsetmd -unsetgt -unsetstats'// TRIM(FNBSQ)
!WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))

! Open and parse BSQ XML:
OPEN(LUINPUT,FILE=TRIM(FNXML),FORM='FORMATTED',STATUS='OLD',IOSTAT=IOS) 
IF (IOS .GT. 0) THEN
   WRITE(*,*) 'Problem opening bsq xml header ', TRIM(FNXML)
ENDIF

WRITE(*,*) 'Reading bsq xml header'

! Trash first five lines
DO I = 1, 5
   READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
ENDDO

! Read number of bands:
READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
READ(TEMPSTR(22:30),*) TEMPSTR
TEMPSTR=TEMPSTR(1:LEN_TRIM(TEMPSTR)-1)
READ(TEMPSTR,*) RASTER%NBANDS
WRITE(*,*) "NBANDS: ", RASTER%NBANDS

READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR ! This is either byte order or band names
IF (LEN_TRIM(TEMPSTR) .GT. 34) THEN !If .TRUE. then we just read band names and need to skip over byte order. 
   READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
ENDIF

! Read data type
READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
READ(TEMPSTR(26:26),*) TEMPSTR
READ(TEMPSTR,*) ITYPE
IF (ITYPE .EQ. 2) THEN
   RASTER%PIXELTYPE='SIGNEDINT'
   RASTER%NBITS=16
ENDIF
IF (ITYPE .EQ. 4) THEN
   RASTER%PIXELTYPE='FLOAT'
   RASTER%NBITS=32
ENDIF
WRITE(*,*) "PIXELTYPE: ", RASTER%PIXELTYPE

! Skip 3 more lines
DO I = 1, 3
   READ(LUINPUT,100,IOSTAT=IOS)
ENDDO

! Read number of rows:
READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
READ(TEMPSTR(22:30),*) TEMPSTR
TEMPSTR=TEMPSTR(1:LEN_TRIM(TEMPSTR)-1)
READ(TEMPSTR,*) RASTER%NROWS

! Read number of columns:
READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
READ(TEMPSTR(24:32),*) TEMPSTR
TEMPSTR=TEMPSTR(1:LEN_TRIM(TEMPSTR)-1)
READ(TEMPSTR,*) RASTER%NCOLS

WRITE(*,*) "NROWS, NCOLS: ", RASTER%NROWS, RASTER%NCOLS

! Set BANDROWBYTES and TOTALROWBYTES:
RASTER%BANDROWBYTES  = (RASTER%NBITS/8) * RASTER%NCOLS
RASTER%TOTALROWBYTES = RASTER%BANDROWBYTES * RASTER%NBANDS

! Skip 5 or 6 more lines
DO I = 1, 5
   READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
ENDDO

IF (LEN_TRIM(TEMPSTR) .LT. 15) THEN !This checks to see if we need to trash one more line
   READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
ENDIF

! Read nodata:
READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
READ(TEMPSTR(18:41),*) TEMPSTR
TEMPSTR=TEMPSTR(1:LEN_TRIM(TEMPSTR)-1)
READ(TEMPSTR,*) RASTER%NODATA_VALUE

WRITE(*,*) "NODATA: ", RASTER%NODATA_VALUE

! Close .xml file:
CLOSE(LUINPUT)

! Open and parse BSQ header:
OPEN(LUINPUT,FILE=TRIM(FNHDR),FORM='FORMATTED',STATUS='OLD',IOSTAT=IOS) 
IF (IOS .GT. 0) THEN
   WRITE(*,*) 'Problem opening bsq header ', TRIM(FNHDR)
ENDIF

WRITE(*,*) 'Reading bsq header'

! Skip 11 lines
DO I = 1, 11
   READ(LUINPUT,100,IOSTAT=IOS)
ENDDO

! Read easting, northing, and cell size info:
READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
FOUND=.FALSE.; I=1
DO WHILE (.NOT. FOUND)
   IF(TEMPSTR(I:I) .EQ. ',') THEN
      FOUND=.TRUE.
   ELSE
      I=I+1
   ENDIF
ENDDO
J=I+1
DO I=1,100
   IF (TEMPSTR(I:I) .EQ. '}') TEMPSTR(I:I)=' '
ENDDO
READ(TEMPSTR(J:),*) IDUMMY, IDUMMY, RASTER%XLLCORNER, RASTER%YLLCORNER, RASTER%XDIM, RASTER%YDIM
RASTER%YLLCORNER = RASTER%YLLCORNER - RASTER%YDIM * RASTER%NROWS
CLOSE(LUINPUT)

!! Check to make sure x and y cell sizes are the same:
!IF (RASTER%XDIM .NE. RASTER%YDIM) THEN
!   WRITE(*,*) 'Error opening ', TRIM(FNHDR), ' because XDIM is not equal to YDIM.'
!   STOP
!ELSE
!   RASTER%CELLSIZE=RASTER%XDIM
!ENDIF

! Set ULXMAP and ULYMAP
RASTER%ULXMAP = RASTER%XLLCORNER + 0.5 * RASTER%XDIM
RASTER%ULYMAP = RASTER%YLLCORNER + RASTER%NROWS * RASTER%YDIM - 0.5 * RASTER%YDIM

!! Set BYTEORDER and LAYOUT
!RASTER%BYTEORDER = '0'
!RASTER%LAYOUT    = 'BSQ'

! This is for bil:
RASTER%BYTEORDER = 'I'
RASTER%LAYOUT    = 'BIL'

SELECT CASE(TRIM(RASTER%PIXELTYPE))

   CASE('FLOAT')
!     Allocate arrays as appropriate:
      IF (.NOT. ALLOCATED(RASTER%RZT)) ALLOCATE(RASTER%RZT(1:RASTER%NBANDS,1:RASTER%NCOLS,1:RASTER%NROWS))
      ALLOCATE(RVALUES(1:RASTER%NROWS*RASTER%NCOLS))
      ALLOCATE(RTEMP(1:RASTER%NCOLS,1:RASTER%NROWS))

!Open raster bsq file:
      INQUIRE (IOLENGTH=LRECL) RVALUES(:) 

      OPEN(LUINPUT, FILE=TRIM(FNBSQ), ACCESS='DIRECT', STATUS='OLD', RECL=LRECL, IOSTAT=IOS) 
      IF (IOS .GT. 0) THEN
         WRITE(*,*) 'Problem opening raster file ', TRIM(FNBSQ)
         STOP
      ENDIF

      DO IBAND = 1, RASTER%NBANDS
         READ(LUINPUT,REC=IBAND,IOSTAT=IOS) RVALUES(:)
         RTEMP(:,:) = RESHAPE(RVALUES, (/RASTER%NCOLS,RASTER%NROWS/))
         DO IROW1 = 1, RASTER%NROWS
            IROW2 = RASTER%NROWS + 1 - IROW1 
            RASTER%RZT(IBAND,:,IROW1) = RTEMP(:,IROW2)
         ENDDO
      ENDDO

      DEALLOCATE(RVALUES, RTEMP)

   CASE('SIGNEDINT')
!     Allocate arrays as appropriate:
      IF (.NOT. ALLOCATED(RASTER%I2ZT)) ALLOCATE(RASTER%I2ZT(1:RASTER%NBANDS,1:RASTER%NCOLS,1:RASTER%NROWS) )
      ALLOCATE(I2VALUES(1:RASTER%NROWS*RASTER%NCOLS))
      ALLOCATE(I2TEMP(1:RASTER%NCOLS,1:RASTER%NROWS))

!Open raster bsq file:
      INQUIRE (IOLENGTH=LRECL) I2VALUES(:) 

      OPEN(LUINPUT, FILE=TRIM(FNBSQ), ACCESS='DIRECT', STATUS='OLD', RECL=LRECL, IOSTAT=IOS) 
      IF (IOS .GT. 0) THEN
         WRITE(*,*) 'Problem opening raster file ', TRIM(FNBSQ)
         STOP
      ENDIF

      DO IBAND = 1, RASTER%NBANDS
         READ(LUINPUT,REC=IBAND,IOSTAT=IOS) I2VALUES(:)
         I2TEMP(:,:) = RESHAPE(I2VALUES, (/RASTER%NCOLS,RASTER%NROWS/))

         DO IROW1 = 1, RASTER%NROWS
            IROW2 = RASTER%NROWS + 1 - IROW1 
            RASTER%I2ZT(IBAND,:,IROW1) = I2TEMP(:,IROW2)
         ENDDO

      ENDDO

      DEALLOCATE(I2VALUES, I2TEMP)

   CASE DEFAULT
      CONTINUE

END SELECT

CLOSE(LUINPUT,IOSTAT=IOS)

SHELLSTR = TRIM(DELETECOMMAND) // " " // TRIM(FNBSQ) // " " // TRIM(FNHDR) // " " // TRIM(FNPRJ) // " " // TRIM(FNXML)
WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))

100 FORMAT(A)

! *****************************************************************************
END SUBROUTINE READ_BSQ_RASTER
! *****************************************************************************

! *****************************************************************************
SUBROUTINE READ_BSQ_RASTER_NEW(RASTER,INDIR,FN)
! *****************************************************************************

USE VARS, ONLY: RASTER_TYPE, LUINPUT, DELETECOMMAND, PATH_TO_GDAL, SCRATCH
#ifdef __INTEL_COMPILER
USE IFPORT
#endif

IMPLICIT NONE

TYPE (RASTER_TYPE), INTENT(OUT) :: RASTER
CHARACTER(400), INTENT (IN) :: INDIR,FN
CHARACTER(400) :: FNHDR, FNBSQ, FNTIF, FNPRJ, FNXML, SHELLSTR, TEMPSTR
INTEGER :: I, J, IOS, LRECL, IBAND, ISTATUS, ITYPE, IDUMMY, IROW1, IROW2
LOGICAL :: FOUND
REAL, ALLOCATABLE, DIMENSION(:) :: RVALUES
REAL, ALLOCATABLE, DIMENSION(:,:) :: RTEMP
INTEGER*2, ALLOCATABLE, DIMENSION(:) :: I2VALUES
INTEGER*2, ALLOCATABLE, DIMENSION(:,:) :: I2TEMP

IF (TRIM(SCRATCH) .EQ. 'null') THEN
   FNTIF = TRIM(INDIR) // TRIM(FN) // '.tif'
   FNHDR = TRIM(INDIR) // TRIM(FN) // '.hdr'
   FNBSQ = TRIM(INDIR) // TRIM(FN) // '.bsq'
   FNPRJ = TRIM(INDIR) // TRIM(FN) // '.prj'
   FNXML = TRIM(FNBSQ) // '.aux.xml'
ELSE
   FNTIF = TRIM(INDIR) // TRIM(FN) // '.tif'
   FNHDR = TRIM(SCRATCH) // TRIM(FN) // '.hdr'
   FNBSQ = TRIM(SCRATCH) // TRIM(FN) // '.bsq'
   FNPRJ = TRIM(SCRATCH) // TRIM(FN) // '.prj'
   FNXML = TRIM(FNBSQ) // '.aux.xml'
ENDIF

! Convert to ENVI header BSQ format
SHELLSTR = TRIM(PATH_TO_GDAL) // 'gdal_translate -of ENVI -co "INTERLEAVE=BSQ" ' // TRIM(FNTIF) // " " // TRIM(FNBSQ)
!SHELLSTR = TRIM(PATH_TO_GDAL) // 'gdalwarp --config GDAL_CACHEMAX 1000 -multi -of ENVI -co "INTERLEAVE=BSQ" ' // TRIM(FNTIF) // " " // TRIM(FNBSQ)
WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))

! Open and parse BSQ XML:
OPEN(LUINPUT,FILE=TRIM(FNXML),FORM='FORMATTED',STATUS='OLD',IOSTAT=IOS) 
IF (IOS .GT. 0) THEN
   WRITE(*,*) 'Problem opening bsq xml header ', TRIM(FNXML)
ENDIF

WRITE(*,*) 'Reading bsq xml header'

! Trash first five lines
DO I = 1, 5
   READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
   CONTINUE
ENDDO

! Read number of bands:
READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
READ(TEMPSTR(22:30),*) TEMPSTR
TEMPSTR=TEMPSTR(1:LEN_TRIM(TEMPSTR)-1)
READ(TEMPSTR,*) RASTER%NBANDS

! Skip over byte order:
READ(LUINPUT,100,IOSTAT=IOS)

! Read data type
READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
READ(TEMPSTR(26:26),*) TEMPSTR
READ(TEMPSTR,*) ITYPE
IF (ITYPE .EQ. 2) THEN
   RASTER%PIXELTYPE='SIGNEDINT'
   RASTER%NBITS=16
ENDIF
IF (ITYPE .EQ. 4) THEN
   RASTER%PIXELTYPE='FLOAT'
   RASTER%NBITS=32
ENDIF

! Skip 3 more lines
DO I = 1, 3
   READ(LUINPUT,100,IOSTAT=IOS)
ENDDO

! Read number of rows:
READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
READ(TEMPSTR(22:30),*) TEMPSTR
TEMPSTR=TEMPSTR(1:LEN_TRIM(TEMPSTR)-1)
READ(TEMPSTR,*) RASTER%NROWS

! Read number of columns:
READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
READ(TEMPSTR(24:32),*) TEMPSTR
TEMPSTR=TEMPSTR(1:LEN_TRIM(TEMPSTR)-1)
READ(TEMPSTR,*) RASTER%NCOLS

! Set BANDROWBYTES and TOTALROWBYTES:
RASTER%BANDROWBYTES  = (RASTER%NBITS/8) * RASTER%NCOLS
RASTER%TOTALROWBYTES = RASTER%BANDROWBYTES * RASTER%NBANDS

! Skip 5 or 6 more lines
DO I = 1, 5
   READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
ENDDO

IF (LEN_TRIM(TEMPSTR) .LT. 15) THEN !This checks to see if we need to trash one more line
   READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
ENDIF

! Read nodata:
READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
READ(TEMPSTR(18:41),*) TEMPSTR
TEMPSTR=TEMPSTR(1:LEN_TRIM(TEMPSTR)-1)
READ(TEMPSTR,*) RASTER%NODATA_VALUE

! Close .xml file:
CLOSE(LUINPUT)

! Open and parse BSQ header:
OPEN(LUINPUT,FILE=TRIM(FNHDR),FORM='FORMATTED',STATUS='OLD',IOSTAT=IOS) 
IF (IOS .GT. 0) THEN
   WRITE(*,*) 'Problem opening bsq header ', TRIM(FNHDR)
ENDIF

WRITE(*,*) 'Reading bsq header'

! Skip 11 lines
DO I = 1, 11
   READ(LUINPUT,100,IOSTAT=IOS)
ENDDO

! Read easting, northing, and cell size info:
READ(LUINPUT,100,IOSTAT=IOS) TEMPSTR
FOUND=.FALSE.; I=1
DO WHILE (.NOT. FOUND)
   IF(TEMPSTR(I:I) .EQ. ',') THEN
      FOUND=.TRUE.
   ELSE
      I=I+1
   ENDIF
ENDDO
J=I+1
DO I=1,100
   IF (TEMPSTR(I:I) .EQ. '}') TEMPSTR(I:I)=' '
ENDDO
READ(TEMPSTR(J:),*) IDUMMY, IDUMMY, RASTER%XLLCORNER, RASTER%YLLCORNER, RASTER%XDIM, RASTER%YDIM
RASTER%YLLCORNER = RASTER%YLLCORNER - RASTER%YDIM * RASTER%NROWS
CLOSE(LUINPUT)

!! Check to make sure x and y cell sizes are the same:
!IF (RASTER%XDIM .NE. RASTER%YDIM) THEN
!   WRITE(*,*) 'Error opening ', TRIM(FNHDR), ' because XDIM is not equal to YDIM.'
!   STOP
!ELSE
!   RASTER%CELLSIZE=RASTER%XDIM
!ENDIF

! Set ULXMAP and ULYMAP
RASTER%ULXMAP = RASTER%XLLCORNER + 0.5 * RASTER%XDIM
RASTER%ULYMAP = RASTER%YLLCORNER + RASTER%NROWS * RASTER%YDIM - 0.5 * RASTER%YDIM

! Set BYTEORDER and LAYOUT
RASTER%BYTEORDER = '0'
RASTER%LAYOUT    = 'BSQ'

! This is for bil:
RASTER%BYTEORDER = 'I'
RASTER%LAYOUT    = 'BIL'

SELECT CASE(TRIM(RASTER%PIXELTYPE))

   CASE('FLOAT')
!     Allocate arrays as appropriate:
      IF (.NOT. ALLOCATED(RASTER%RZT)) ALLOCATE(RASTER%RZT(1:RASTER%NBANDS,1:RASTER%NCOLS,1:RASTER%NROWS))
      ALLOCATE(RVALUES(1:RASTER%NROWS*RASTER%NCOLS))
      ALLOCATE(RTEMP(1:RASTER%NCOLS,1:RASTER%NROWS))

!Open raster bsq file:
      INQUIRE (IOLENGTH=LRECL) RVALUES(:) 

      OPEN(LUINPUT, FILE=TRIM(FNBSQ), ACCESS='DIRECT', STATUS='OLD', RECL=LRECL, IOSTAT=IOS) 
      IF (IOS .GT. 0) THEN
         WRITE(*,*) 'Problem opening raster file ', TRIM(FNBSQ)
         STOP
      ENDIF

      DO IBAND = 1, RASTER%NBANDS
         READ(LUINPUT,REC=IBAND,IOSTAT=IOS) RVALUES(:)
         RTEMP(:,:) = RESHAPE(RVALUES, (/RASTER%NCOLS,RASTER%NROWS/))
         DO IROW1 = 1, RASTER%NROWS
            IROW2 = RASTER%NROWS + 1 - IROW1 
            RASTER%RZT(IBAND,:,IROW1) = RTEMP(:,IROW2)
         ENDDO
      ENDDO

      DEALLOCATE(RVALUES, RTEMP)

   CASE('SIGNEDINT')
!     Allocate arrays as appropriate:
      IF (.NOT. ALLOCATED(RASTER%I2ZT)) ALLOCATE(RASTER%I2ZT(1:RASTER%NBANDS,1:RASTER%NCOLS,1:RASTER%NROWS) )
      ALLOCATE(I2VALUES(1:RASTER%NROWS*RASTER%NCOLS))
      ALLOCATE(I2TEMP(1:RASTER%NCOLS,1:RASTER%NROWS))

!Open raster bsq file:
      INQUIRE (IOLENGTH=LRECL) I2VALUES(:) 

      OPEN(LUINPUT, FILE=TRIM(FNBSQ), ACCESS='DIRECT', STATUS='OLD', RECL=LRECL, IOSTAT=IOS) 
      IF (IOS .GT. 0) THEN
         WRITE(*,*) 'Problem opening raster file ', TRIM(FNBSQ)
         STOP
      ENDIF

      DO IBAND = 1, RASTER%NBANDS
         READ(LUINPUT,REC=IBAND,IOSTAT=IOS) I2VALUES(:)
         I2TEMP(:,:) = RESHAPE(I2VALUES, (/RASTER%NCOLS,RASTER%NROWS/))

         DO IROW1 = 1, RASTER%NROWS
            IROW2 = RASTER%NROWS + 1 - IROW1 
            RASTER%I2ZT(IBAND,:,IROW1) = I2TEMP(:,IROW2)
         ENDDO

      ENDDO

      DEALLOCATE(I2VALUES, I2TEMP)

   CASE DEFAULT
      CONTINUE

END SELECT

CLOSE(LUINPUT,IOSTAT=IOS)

SHELLSTR = TRIM(DELETECOMMAND) // " " // TRIM(FNBSQ) // " " // TRIM(FNHDR) // " " // TRIM(FNPRJ) // " " // TRIM(FNXML)
WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))

100 FORMAT(A)

! *****************************************************************************
END SUBROUTINE READ_BSQ_RASTER_NEW
! *****************************************************************************

! *****************************************************************************
SUBROUTINE WRITE_BIL_RASTER_NEW(RASTER, INDIR, FN, CONVERT_TO_GEOTIFF, COMPRESS)
! *****************************************************************************

USE VARS, ONLY: RASTER_TYPE, LUOUTPUT, A_SRS, DELETECOMMAND, PATH_TO_GDAL, SCRATCH
#ifdef __INTEL_COMPILER
USE IFPORT
#endif

IMPLICIT NONE

TYPE (RASTER_TYPE), INTENT(IN) :: RASTER
CHARACTER(400), INTENT(IN) :: INDIR,FN
LOGICAL, INTENT(IN) :: CONVERT_TO_GEOTIFF,COMPRESS
CHARACTER(400) :: SHELLSTR,FNBIL,FNHDR,FNTIF
INTEGER :: IOS, IROW, ICOL, IBAND, ISTATUS
REAL, ALLOCATABLE, DIMENSION(:) ::  RVALUES
INTEGER           :: ICOLSTART, ICOLSTOP, IROWSTART, IROWSTOP, LRECL, IREC
INTEGER*2, ALLOCATABLE, DIMENSION(:) :: I2VALUES

IF (TRIM(SCRATCH) .EQ. 'null') THEN
   FNTIF = TRIM(INDIR) // TRIM(FN) // '.tif'
   FNHDR = TRIM(INDIR) // TRIM(FN) // '.hdr'
   FNBIL = TRIM(INDIR) // TRIM(FN) // '.bil'
ELSE
   FNTIF = TRIM(INDIR  ) // TRIM(FN) // '.tif'
   FNHDR = TRIM(SCRATCH) // TRIM(FN) // '.hdr'
   FNBIL = TRIM(SCRATCH) // TRIM(FN) // '.bil'
ENDIF

ICOLSTART  = 1 
ICOLSTOP   = RASTER%NCOLS
IROWSTART  = 1
IROWSTOP   = RASTER%NROWS

!Open and write hdr file:
OPEN(LUOUTPUT,FILE=TRIM(FNHDR),FORM='FORMATTED',STATUS='REPLACE',IOSTAT=IOS)

WRITE(LUOUTPUT,110,IOSTAT=IOS) 'BYTEORDER      ', TRIM(RASTER%BYTEORDER)
WRITE(LUOUTPUT,110,IOSTAT=IOS) 'LAYOUT         ', TRIM(RASTER%LAYOUT)
WRITE(LUOUTPUT,300,IOSTAT=IOS) 'NROWS          ', RASTER%NROWS 
WRITE(LUOUTPUT,300,IOSTAT=IOS) 'NCOLS          ', RASTER%NCOLS
WRITE(LUOUTPUT,300,IOSTAT=IOS) 'NBANDS         ', RASTER%NBANDS
WRITE(LUOUTPUT,300,IOSTAT=IOS) 'NBITS          ', RASTER%NBITS
WRITE(LUOUTPUT,300,IOSTAT=IOS) 'BANDROWBYTES   ', RASTER%BANDROWBYTES  !4*RASTER%NCOLS
WRITE(LUOUTPUT,300,IOSTAT=IOS) 'TOTALROWBYTES  ', RASTER%TOTALROWBYTES !4*RASTER%NBANDS*RASTER%NCOLS 
WRITE(LUOUTPUT,110,IOSTAT=IOS) 'PIXELTYPE      ', TRIM(RASTER%PIXELTYPE)
WRITE(LUOUTPUT,400,IOSTAT=IOS) 'ULXMAP         ', RASTER%ULXMAP
WRITE(LUOUTPUT,400,IOSTAT=IOS) 'ULYMAP         ', RASTER%ULYMAP
WRITE(LUOUTPUT,400,IOSTAT=IOS) 'XDIM           ', RASTER%XDIM
WRITE(LUOUTPUT,400,IOSTAT=IOS) 'YDIM           ', RASTER%YDIM
WRITE(LUOUTPUT,400,IOSTAT=IOS) 'NODATA         ', RASTER%NODATA_VALUE
CLOSE(LUOUTPUT,IOSTAT=IOS)

!Open and write raster file:

SELECT CASE (TRIM(RASTER%PIXELTYPE))

   CASE ('FLOAT') 

      ALLOCATE(RVALUES(1:RASTER%NCOLS*RASTER%NBANDS))

      INQUIRE (IOLENGTH=LRECL) RVALUES(:)
      OPEN(LUOUTPUT,FILE=TRIM(FNBIL),ACCESS='DIRECT',STATUS='REPLACE',RECL=LRECL,IOSTAT=IOS) 
      IF (IOS .GT. 0) THEN
         WRITE(*,*) 'Problem opening output bil file ', TRIM(FNBIL)
         STOP
      ENDIF

      IREC = 0
      DO IROW = IROWSTOP, IROWSTART, -1

         IREC = IREC + 1
         RVALUES(:) = REAL(RASTER%NODATA_VALUE)
   
         ICOLSTART = 1
         DO IBAND = 1, RASTER%NBANDS
            ICOLSTOP  = ICOLSTART + RASTER%NCOLS - 1
            RVALUES(ICOLSTART:ICOLSTOP) = RASTER%RZT(IBAND,1:RASTER%NCOLS,IROW)   
            ICOLSTART = ICOLSTOP + 1
         ENDDO
   
         WRITE(LUOUTPUT,REC=IREC,IOSTAT=IOS) (RVALUES(ICOL), ICOL=1, ICOLSTOP)
   
      ENDDO

      FLUSH(LUOUTPUT)

      CLOSE(LUOUTPUT,IOSTAT=IOS)

      DEALLOCATE(RVALUES)

      IF (CONVERT_TO_GEOTIFF) THEN
         IF (COMPRESS) THEN
            SHELLSTR = TRIM(PATH_TO_GDAL) // 'gdal_translate -ot Float32 -co "COMPRESS=DEFLATE" -co "ZLEVEL=9" -a_srs "' // &
                       TRIM(A_SRS) // '" ' // TRIM(FNBIL) // ' ' // TRIM(FNTIF)
            WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))
         ELSE
            SHELLSTR = TRIM(PATH_TO_GDAL) // 'gdal_translate -ot Float32 -a_srs "' // &
                       TRIM(A_SRS) // '" ' // TRIM(FNBIL) // ' '// TRIM(FNTIF)
            WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))   
         ENDIF

         SHELLSTR = TRIM(DELETECOMMAND) // " " // TRIM(FNBIL); WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))
         SHELLSTR = TRIM(DELETECOMMAND) // " " // TRIM(FNHDR); WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))
      ENDIF

   CASE ('SIGNEDINT') 

      ALLOCATE(I2VALUES(1:RASTER%NCOLS*RASTER%NBANDS))

      INQUIRE (IOLENGTH = LRECL) I2VALUES(:)
      OPEN(LUOUTPUT,FILE=TRIM(FNBIL),ACCESS='DIRECT',STATUS='REPLACE',RECL=LRECL,IOSTAT=IOS) 
      IF (IOS .GT. 0) THEN
         WRITE(*,*) 'Problem opening output bil file ', TRIM(FNBIL)
         STOP
      ENDIF

      IREC = 0
      DO IROW = IROWSTOP, IROWSTART, -1

         IREC = IREC + 1
         I2VALUES(:) = NINT(RASTER%NODATA_VALUE)
   
         ICOLSTART = 1
         DO IBAND = 1, RASTER%NBANDS
            ICOLSTOP  = ICOLSTART + RASTER%NCOLS - 1
            I2VALUES(ICOLSTART:ICOLSTOP) = RASTER%I2ZT(IBAND,1:RASTER%NCOLS,IROW)   
            ICOLSTART = ICOLSTOP + 1
         ENDDO
   
         WRITE(LUOUTPUT,REC=IREC,IOSTAT=IOS) (I2VALUES(ICOL), ICOL=1, ICOLSTOP)
   
      ENDDO

      FLUSH(LUOUTPUT)

      CLOSE(LUOUTPUT,IOSTAT=IOS)

      DEALLOCATE(I2VALUES)

      IF (CONVERT_TO_GEOTIFF) THEN
         IF (COMPRESS) THEN
            SHELLSTR = TRIM(PATH_TO_GDAL) // 'gdal_translate -ot Int16 -co "COMPRESS=DEFLATE" -co "ZLEVEL=9" -a_srs "' // &
                       TRIM(A_SRS) // '" ' // TRIM(FNBIL) // ' ' // TRIM(FNTIF)
            WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))
         ELSE
            SHELLSTR = TRIM(PATH_TO_GDAL) // 'gdal_translate -ot Int16 -a_srs "' // &
                       TRIM(A_SRS) // '" ' // TRIM(FNBIL) // ' ' // TRIM(FNTIF)
            WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))   
         ENDIF

         SHELLSTR = TRIM(DELETECOMMAND) // " " // TRIM(FNBIL); WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))
         SHELLSTR = TRIM(DELETECOMMAND) // " " // TRIM(FNHDR); WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))
      ENDIF

   CASE DEFAULT
      CONTINUE

END SELECT

100 FORMAT(A)
110 FORMAT(A,A)

300 FORMAT(A, I8)
400 FORMAT(A, F12.2)

! *****************************************************************************
END SUBROUTINE WRITE_BIL_RASTER_NEW
! *****************************************************************************

! *****************************************************************************
SUBROUTINE WRITE_BIL_RASTER(RASTER, INDIR, FN, CONVERT_TO_GEOTIFF, COMPRESS)
! *****************************************************************************

USE VARS, ONLY: RASTER_TYPE, LUOUTPUT, A_SRS, DELETECOMMAND, PATH_TO_GDAL, SCRATCH
#ifdef __INTEL_COMPILER
USE IFPORT
#endif

IMPLICIT NONE

TYPE (RASTER_TYPE), INTENT(IN) :: RASTER
CHARACTER(400), INTENT(IN) :: INDIR,FN
LOGICAL, INTENT(IN) :: CONVERT_TO_GEOTIFF,COMPRESS
CHARACTER(400) :: SHELLSTR,FNBIL,FNHDR,FNTIF
INTEGER :: IOS, IROW, ICOL, IBAND, ISTATUS
REAL, ALLOCATABLE, DIMENSION(:) ::  RVALUES
INTEGER           :: ICOLSTART, ICOLSTOP, IROWSTART, IROWSTOP, LRECL, IREC
INTEGER*2, ALLOCATABLE, DIMENSION(:) :: I2VALUES

IF (TRIM(SCRATCH) .EQ. 'null') THEN
   FNTIF = TRIM(INDIR) // TRIM(FN) // '.tif'
   FNHDR = TRIM(INDIR) // TRIM(FN) // '.hdr'
   FNBIL = TRIM(INDIR) // TRIM(FN) // '.bil'
ELSE
   FNTIF = TRIM(INDIR  ) // TRIM(FN) // '.tif'
   FNHDR = TRIM(SCRATCH) // TRIM(FN) // '.hdr'
   FNBIL = TRIM(SCRATCH) // TRIM(FN) // '.bil'
ENDIF

ICOLSTART  = 1 
ICOLSTOP   = RASTER%NCOLS
IROWSTART  = 1
IROWSTOP   = RASTER%NROWS

!Open and write hdr file:
OPEN(LUOUTPUT,FILE=TRIM(FNHDR),FORM='FORMATTED',STATUS='REPLACE',IOSTAT=IOS)

WRITE(LUOUTPUT,110,IOSTAT=IOS) 'BYTEORDER      ', TRIM(RASTER%BYTEORDER)
WRITE(LUOUTPUT,110,IOSTAT=IOS) 'LAYOUT         ', TRIM(RASTER%LAYOUT)
WRITE(LUOUTPUT,300,IOSTAT=IOS) 'NROWS          ', RASTER%NROWS 
WRITE(LUOUTPUT,300,IOSTAT=IOS) 'NCOLS          ', RASTER%NCOLS
WRITE(LUOUTPUT,300,IOSTAT=IOS) 'NBANDS         ', RASTER%NBANDS
WRITE(LUOUTPUT,300,IOSTAT=IOS) 'NBITS          ', RASTER%NBITS
WRITE(LUOUTPUT,300,IOSTAT=IOS) 'BANDROWBYTES   ', RASTER%BANDROWBYTES  !4*RASTER%NCOLS
WRITE(LUOUTPUT,300,IOSTAT=IOS) 'TOTALROWBYTES  ', RASTER%TOTALROWBYTES !4*RASTER%NBANDS*RASTER%NCOLS 
WRITE(LUOUTPUT,110,IOSTAT=IOS) 'PIXELTYPE      ', TRIM(RASTER%PIXELTYPE)
WRITE(LUOUTPUT,400,IOSTAT=IOS) 'ULXMAP         ', RASTER%ULXMAP
WRITE(LUOUTPUT,400,IOSTAT=IOS) 'ULYMAP         ', RASTER%ULYMAP
WRITE(LUOUTPUT,400,IOSTAT=IOS) 'XDIM           ', RASTER%XDIM
WRITE(LUOUTPUT,400,IOSTAT=IOS) 'YDIM           ', RASTER%YDIM
WRITE(LUOUTPUT,400,IOSTAT=IOS) 'NODATA         ', RASTER%NODATA_VALUE
CLOSE(LUOUTPUT,IOSTAT=IOS)

!Open and write raster file:

SELECT CASE (TRIM(RASTER%PIXELTYPE))

   CASE ('FLOAT') 

      ALLOCATE(RVALUES(1:RASTER%NCOLS*RASTER%NBANDS))

      INQUIRE (IOLENGTH=LRECL) RVALUES(:)
      OPEN(LUOUTPUT,FILE=TRIM(FNBIL),ACCESS='DIRECT',STATUS='REPLACE',RECL=LRECL,IOSTAT=IOS) 
      IF (IOS .GT. 0) THEN
         WRITE(*,*) 'Problem opening output bil file ', TRIM(FNBIL)
         STOP
      ENDIF

      IREC = 0
      DO IROW = IROWSTOP, IROWSTART, -1

         IREC = IREC + 1
         RVALUES(:) = REAL(RASTER%NODATA_VALUE)
   
         ICOLSTART = 1
         DO IBAND = 1, RASTER%NBANDS
            ICOLSTOP  = ICOLSTART + RASTER%NCOLS - 1
            RVALUES(ICOLSTART:ICOLSTOP) = RASTER%RZT(IBAND,1:RASTER%NCOLS,IROW)   
            ICOLSTART = ICOLSTOP + 1
         ENDDO
   
         WRITE(LUOUTPUT,REC=IREC,IOSTAT=IOS) (RVALUES(ICOL), ICOL=1, ICOLSTOP)
   
      ENDDO

      FLUSH(LUOUTPUT)

      CLOSE(LUOUTPUT,IOSTAT=IOS)

      DEALLOCATE(RVALUES)

      IF (CONVERT_TO_GEOTIFF) THEN
         IF (COMPRESS) THEN
            SHELLSTR = TRIM(PATH_TO_GDAL) // 'gdal_translate -ot Float32 -co "COMPRESS=DEFLATE" -co "ZLEVEL=9" -a_srs "' // &
                       TRIM(A_SRS) // '" ' // TRIM(FNBIL) // ' ' // TRIM(FNTIF)
            WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))
         ELSE
            SHELLSTR = TRIM(PATH_TO_GDAL) // 'gdal_translate -ot Float32 -a_srs "' // &
                       TRIM(A_SRS) // '" ' // TRIM(FNBIL) // ' '// TRIM(FNTIF)
            WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))   
         ENDIF

         SHELLSTR = TRIM(DELETECOMMAND) // " " // TRIM(FNBIL); WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))
         SHELLSTR = TRIM(DELETECOMMAND) // " " // TRIM(FNHDR); WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))
      ENDIF

   CASE ('SIGNEDINT') 

      ALLOCATE(I2VALUES(1:RASTER%NCOLS*RASTER%NBANDS))

      INQUIRE (IOLENGTH = LRECL) I2VALUES(:)
      OPEN(LUOUTPUT,FILE=TRIM(FNBIL),ACCESS='DIRECT',STATUS='REPLACE',RECL=LRECL,IOSTAT=IOS) 
      IF (IOS .GT. 0) THEN
         WRITE(*,*) 'Problem opening output bil file ', TRIM(FNBIL)
         STOP
      ENDIF

      IREC = 0
      DO IROW = IROWSTOP, IROWSTART, -1

         IREC = IREC + 1
         I2VALUES(:) = NINT(RASTER%NODATA_VALUE,KIND=2)
   
         ICOLSTART = 1
         DO IBAND = 1, RASTER%NBANDS
            ICOLSTOP  = ICOLSTART + RASTER%NCOLS - 1
            I2VALUES(ICOLSTART:ICOLSTOP) = RASTER%I2ZT(IBAND,1:RASTER%NCOLS,IROW)   
            ICOLSTART = ICOLSTOP + 1
         ENDDO

         WRITE(LUOUTPUT,REC=IREC,IOSTAT=IOS) (I2VALUES(ICOL), ICOL=1, ICOLSTOP)
   
      ENDDO

      FLUSH(LUOUTPUT)

      CLOSE(LUOUTPUT,IOSTAT=IOS)

      DEALLOCATE(I2VALUES)

      IF (CONVERT_TO_GEOTIFF) THEN
         IF (COMPRESS) THEN
            SHELLSTR = TRIM(PATH_TO_GDAL) // 'gdal_translate -ot Int16 -co "COMPRESS=DEFLATE" -co "ZLEVEL=9" -a_srs "' // &
                       TRIM(A_SRS) // '" ' // TRIM(FNBIL) // ' ' // TRIM(FNTIF)
            WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))
         ELSE
            SHELLSTR = TRIM(PATH_TO_GDAL) // 'gdal_translate -ot Int16 -a_srs "' // &
                       TRIM(A_SRS) // '" ' // TRIM(FNBIL) // ' ' // TRIM(FNTIF)
            WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))   
         ENDIF

         SHELLSTR = TRIM(DELETECOMMAND) // " " // TRIM(FNBIL); WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))
         SHELLSTR = TRIM(DELETECOMMAND) // " " // TRIM(FNHDR); WRITE(*,100) TRIM(SHELLSTR); ISTATUS = SYSTEM(TRIM(SHELLSTR))
      ENDIF

   CASE DEFAULT
      CONTINUE

END SELECT

100 FORMAT(A)
110 FORMAT(A,A)

300 FORMAT(A, I8)
400 FORMAT(A, F12.2)

! *****************************************************************************
END SUBROUTINE WRITE_BIL_RASTER
! *****************************************************************************

! *****************************************************************************
SUBROUTINE ALLOCATE_EMPTY_RASTER(RASTER,NCOLS,NROWS,NBANDS,XLLCORNER,YLLCORNER,XDIM,YDIM,NODATA_VALUE,ITYPE,PIXELTYPE)
! *****************************************************************************

USE VARS, ONLY: RASTER_TYPE

IMPLICIT NONE

TYPE(RASTER_TYPE), INTENT(INOUT) :: RASTER
INTEGER, INTENT(IN) :: NCOLS, NROWS, NBANDS
REAL, INTENT(IN) :: XLLCORNER, YLLCORNER, XDIM, YDIM, NODATA_VALUE
INTEGER, INTENT(IN) :: ITYPE !ITYPE = 1 allocates Z; ITYPE = 2 allocates ZT; ITYPE = 3 allocates both
CHARACTER(10), INTENT(IN) :: PIXELTYPE
INTEGER :: NBITS

IF (ITYPE .NE. 1 .AND. ITYPE .NE. 2 .AND. ITYPE .NE. 3) THEN
   WRITE(*,*) 'ERROR IN ALLOCATE_EMPTY_RASTER BECAUSE ITYPE < 1 OR > 3'
   STOP   
ENDIF

IF (TRIM(PIXELTYPE) .NE. 'FLOAT' .AND. TRIM(PIXELTYPE) .NE. 'SIGNEDINT' ) THEN
   WRITE(*,*) "Error in ALLOCATE_EMPTY_RASTER. For now, only available PIXELTYPE are 'FLOAT' and 'SIGNEDINT'."
   STOP
ENDIF

SELECT CASE(TRIM(PIXELTYPE))
   CASE('FLOAT')
      NBITS=32
   CASE('SIGNEDINT')
      NBITS=16

   CASE DEFAULT
      CONTINUE
END SELECT

! Thse three variables are used by ELMFIRE but are not in the BIL header:
RASTER%XLLCORNER    = XLLCORNER
RASTER%YLLCORNER    = YLLCORNER
!RASTER%CELLSIZE     = CELLSIZE

! These variables, in order, get written to the BIL header
RASTER%BYTEORDER     = 'I'
RASTER%LAYOUT        = 'BIL'
RASTER%NROWS         = NROWS
RASTER%NCOLS         = NCOLS
RASTER%NBANDS        = NBANDS
RASTER%NBITS         = NBITS
RASTER%BANDROWBYTES  = (RASTER%NBITS/8) * RASTER%NCOLS
RASTER%TOTALROWBYTES = RASTER%BANDROWBYTES * RASTER%NBANDS
RASTER%PIXELTYPE     = PIXELTYPE
RASTER%XDIM          = XDIM
RASTER%YDIM          = YDIM
RASTER%ULXMAP        = RASTER%XLLCORNER + 0.5*RASTER%XDIM
RASTER%ULYMAP        = RASTER%YLLCORNER - 0.5*RASTER%YDIM + REAL(RASTER%NROWS)*RASTER%YDIM
RASTER%NODATA_VALUE  = NODATA_VALUE
 
SELECT CASE(TRIM(PIXELTYPE))
   CASE('FLOAT')
      ALLOCATE(RASTER%RZT(1:NBANDS,1:NCOLS,1:NROWS))
      RASTER%RZT(:,:,:) = NODATA_VALUE
   CASE('SIGNEDINT')
      ALLOCATE(RASTER%I2ZT(1:NBANDS,1:NCOLS,1:NROWS))
      RASTER%I2ZT(:,:,:) = NINT(NODATA_VALUE)
   CASE DEFAULT
      CONTINUE
END SELECT

! *****************************************************************************
END SUBROUTINE ALLOCATE_EMPTY_RASTER
! *****************************************************************************

! *****************************************************************************
END MODULE IO
! *****************************************************************************
